# =========================================
# APPLICATION NAME
# =========================================
spring.application.name=backend

# =========================================
# SERVER CONFIG
# =========================================
server.port=${PORT:8080}

# =========================================
# DATABASE CONFIG
# =========================================
spring.datasource.url=spring.datasource.url=jdbc:postgresql://dpg-d84su4d8nd3s73d9kqk0-a.oregon-postgres.render.com:5432/productdb_1o8a?sslmode=require
spring.datasource.username=productuser
spring.datasource.password=OJ9ecff4YqMXIUhfLCC35L7woAX3joqZ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
# =========================================
# JPA / HIBERNATE CONFIG
# =========================================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================================
# CORS CONFIG
# =========================================
spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*

# =========================================
# FILE UPLOAD
# =========================================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# =========================================
# JACKSON
# =========================================
spring.jackson.serialization.fail-on-empty-beans=false